name: foodfleet
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  provider: ^6.1.5+1
  flutter_spinkit: ^5.2.2
  fluttertoast: ^8.2.8 
  intl: ^0.20.2
  image_picker: ^1.2.0
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.4.0
  permission_handler: ^10.4.0
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0

flutter:

  
  uses-material-design: true

  assets:
     - assets/delivery1.jpg
     - assets/delivery2.jpg
     - assets/favfood1.jpg
     - assets/favfood2.jpg
     - assets/favfood3.jpg
     - assets/favfood4.jpg
     - assets/log1.png
     - assets/google.jpg
     - assets/apple.jpg
     - assets/congrats.json
     - assets/f1.jpg
     - assets/f2.jpg
     - assets/f3.jpg
     - assets/f4.jpg
     - assets/f5.jpg
     - assets/f6.jpg
     - assets/f7.jpg
     - assets/f8.jpg
     - assets/brownugali.jpg
     - assets/ChapatiBeef.jpg
     - assets/ChipsMasala.jpg
     - assets/pilau.jpg
     - assets/FriedFishwithwhiteRice.jpg
     - assets/Githeri.jpg
     - assets/JolloRice.jpg
     - assets/ZambianNshimaFishwithVeggies.jpg
     - assets/chickenTeriyaki.jpg
     - assets/mpesa.png
     - assets/creditcard.jpg

 